### ISSUE TITLE
undefined method 'maximum' (on 2.6.9)

### ISSUE THREAD

**Issue by DarkSideGeek** [jbbarth/redmine_reminders#3]
I originally thought this was a conflict with the sudo plugin, because I only saw this error when elevated to Admin mode. But that was only because I hadn't added REMINDER permission to mortal roles. Now I get the following as anyone:

```
Started GET "/my/page" for 192.168.1.77 at 2016-01-13 18:53:38 -0800
Processing by MyController#page as HTML
  Current user: bhoule (id=3)
DEPRECATION WARNING: #link_to_project with :action option is deprecated and will be removed in Redmine 3.0. (called from link_to_project at /var/www/apps/redmine-2.6.9/app/helpers/application_helper.rb:141)
DEPRECATION WARNING: #link_to_project with :action option is deprecated and will be removed in Redmine 3.0. (called from link_to_project at /var/www/apps/redmine-2.6.9/app/helpers/application_helper.rb:141)
  Rendered plugins/redmine_favourite_projects/app/views/my/blocks/_favourite_projects_box.html.erb (30.0ms)
  Rendered plugins/redmine_dmsf/app/views/my/blocks/_open_approvals.html.erb (1.0ms)
  Rendered plugins/redmine_my_page_queries/app/views/my/blocks/_label_my_queries.html.erb (2.5ms)
  Rendered issues/_list_simple.html.erb (6.5ms)
  Rendered my/blocks/_issuesassignedtome.html.erb (20.9ms)
  Rendered issues/_list_simple.html.erb (17.5ms)
  Rendered my/blocks/_issuesreportedbyme.html.erb (27.6ms)
  Rendered common/_calendar.html.erb (5.4ms)
  Rendered my/blocks/_calendar.html.erb (14.6ms)
  Rendered news/_news.html.erb (1.2ms)
  Rendered my/blocks/_news.html.erb (4.9ms)
  Rendered issues/_list_simple.html.erb (0.2ms)
  Rendered my/blocks/_issueswatched.html.erb (6.6ms)
Deface: [ERROR] The original source for 'add-new-reminder-link-to-my-page' has changed, this override should be reviewed to ensure it's still valid.
Deface: [ERROR] The original source for 'add-visible-reminders-on-my-page' has changed, this override should be reviewed to ensure it's still valid.
  Rendered plugins/redmine_my_page_queries/app/views/my/page.html.erb within layouts/base (216.8ms)
Completed 500 Internal Server Error in 222.6ms

ActionView::Template::Error (undefined method `maximum' for Reminder:Module):
    24: </div>
    25:
    26: <div id="list-right" class="splitcontentright">
    27: <% if User.current.allowed_to?(:view_reminders, nil, :global => true) %><% cache ["reminders-on-my-page", "v2", Date.today, User.current, Reminder.maximum(:updated_at)] do %><% reminders = Reminder.visible.current.order("end_at") %><% if reminders.any? %><div class="reminders">
    28:         <h3><%= l(:label_reminder_plural) %></h3>
    29:         <% reminders.each do |reminder| %><%= content_tag :div, :class => "reminder reminder-#{reminder.color}" do %><%= textilizable reminder.text %><em class="info">
    30:               <%= reminder.user %> |
  plugins/redmine_my_page_queries/app/views/my/page.html.erb:27:in `_4a518ea94046706f9a004b9db4bdd0ce'
  actionpack (3.2.22) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.22) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.22) lib/action_view/template.rb:143:in `render'
  deface (1.0.2) lib/deface/action_view_extensions.rb:41:in `render'
  actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
  actionpack (3.2.22) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (3.2.22) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.22) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.22) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.22) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
  actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:18:in `render'
  actionpack (3.2.22) lib/action_view/renderer/renderer.rb:36:in `render_template'
  actionpack (3.2.22) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.22) lib/abstract_controller/rendering.rb:110:in `_render_template'
  actionpack (3.2.22) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.22) lib/abstract_controller/rendering.rb:103:in `render_to_body'
  actionpack (3.2.22) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.22) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  actionpack (3.2.22) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.22) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  activesupport (3.2.22) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /usr/local/rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  activesupport (3.2.22) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  activerecord (3.2.22) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:39:in `render'
  actionpack (3.2.22) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (3.2.22) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (3.2.22) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.22) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.22) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.22) lib/active_support/callbacks.rb:513:in `_run__1960378954699104952__process_action__2117454149084409945__callbacks'
  activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.22) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.22) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.22) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.22) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.22) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.22) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.22) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.22) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.22) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.22) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.22) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.22) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-raw-upload (1.1.1) lib/rack/raw_upload.rb:18:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.7) lib/rack/etag.rb:23:in `call'
  rack (1.4.7) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.22) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.22) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `_run__3157174683881020294__call__729527519723701246__callbacks'
  activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.22) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.22) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.22) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.22) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.22) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.22) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.5.1) lib/rack/cache/context.rb:140:in `forward'
  rack-cache (1.5.1) lib/rack/cache/context.rb:249:in `fetch'
  rack-cache (1.5.1) lib/rack/cache/context.rb:189:in `lookup'
  rack-cache (1.5.1) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.5.1) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.22) lib/rails/engine.rb:484:in `call'
  railties (3.2.22) lib/rails/application.rb:231:in `call'
  railties (3.2.22) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.5) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  passenger (4.0.5) lib/phusion_passenger/request_handler/thread_handler.rb:140:in `accept_and_process_next_request'
  passenger (4.0.5) lib/phusion_passenger/request_handler/thread_handler.rb:108:in `main_loop'
  passenger (4.0.5) lib/phusion_passenger/request_handler.rb:441:in `block (3 levels) in start_threads'

```

**Comment by nanego** [comment]
Working with Redmine 2.6.x, you should not use the latest version of this plugin which has been updated to be compatible with Redmine 3.
Use instead the 0.0.1 version here: https://github.com/jbbarth/redmine_reminders/tree/v0.0.1

**Comment by DarkSideGeek** [comment]
No luck. Checking out against the 0.0.1 tag still results in the following (different) error:
````
Completed 500 Internal Server Error in 280.0ms

ActionView::Template::Error (undefined method `order' for Reminder:Module):
    24: </div>
    25:
    26: <div id="list-right" class="splitcontentright">
    27: <% if User.current.allowed_to?(:view_reminders, nil, :global => true) %><% cache ["reminders-on-my-page", "v2", Date.today, User.current, Reminder.order("updated_at").last] do %><% reminders = Reminder.visible.current.order("end_at") %><% if reminders.any? %><div class="reminders">
    28:         <h3><%= l(:label_reminder_plural) %></h3>
    29:         <% reminders.each do |reminder| %><%= content_tag :div, :class => "reminder reminder-#{reminder.color}" do %><%= textilizable reminder.text %><em class="info">
    30:               <%= reminder.user %> |
  plugins/redmine_my_page_queries/app/views/my/page.html.erb:27:in `_a5634f5d877710d85a1c33e99640af16'
````

**Comment by nanego** [comment]
I am closing this (too old) issue. It was certainly due to a conflict with another plugin.
